### ISSUE TITLE
Volume percentage

### ISSUE THREAD

**Issue by Xitro01** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#12]
Great add-on to begin with, actually the only one that works well with the Samsung Soundbars.

I have a small feature request: If you set the "max_volume: 50" and you set the volume all the way up, the volume shows as 100 (%) in HomeAssistant. Would it be possible to change that into the absolute volume and not the percentage? This way I can more accurately set my volume to for example "20".

Thank you in advance!

**Comment by PiotrMachowski** [comment]
@Xitro01 actually [my version of built-in SmartThings integration](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings) works as well ;)

If you want to set your volume accurately you would have to remove `max_volume` from your config. HA works with percentage and I used scaled version on purpose, because if you set max_volume to ~20 then you don't have to be so precise with volume slider in HA

**Comment by Xitro01** [comment]
> @Xitro01 actually [my version of built-in SmartThings integration](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings) works as well ;)
> 
> If you want to set your volume accurately you would have to remove `max_volume` from your config. HA works with percentage and I used scaled version on purpose, because if you set max_volume to ~20 then you don't have to be so precise with volume slider in HA

I actually like to have it scaled and have a max of 50, as it indeed blows your windows out if you set your volume at 100.
But it would be nice to actually see the exact volume that you're putting it on. Not that if you put it on 24, that it's actually 12 on the soundbar. There is no way to make this work 1:1 with a max of 50 for example?

**Comment by PiotrMachowski** [comment]
Unfortunately it's not possible :( I can add an attribute that will show an actual volume, but you won't see it on slider

**Comment by Xitro01** [comment]
Too bad, would've been great. Thank you!
